name: Update Top 5 Blogs

on:
  schedule:
    - cron: "12 2 * * *"   # daily 02:12 UTC
  workflow_dispatch:
  push:
    paths:
      - scripts/update_blogs.py
      - .github/workflows/update-blogs.yml
      - README.md

permissions:
  contents: write

jobs:
  update-blogs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update README Latest Blogs
        run: python scripts/update_blogs.py

      - name: Commit & Push (if changed)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update latest blog posts [skip ci]"
            git push
          else
            echo "No changes."
          fi
